---

# Implement your Workload removal tasks here

- name: define ocp project
  set_fact:
    ocp_project: "rhsso-{{ guid }}"

- name: delete limitrange in namespace
  k8s:
    state: absent
    namespace: "{{ ocp_project }}"
    definition: "{{ lookup('template', role_path ~ '/templates/limitrange.j2' ) | from_yaml }}"

- name: delete project for user
  k8s:
    state: absent
    definition: "{{ lookup('template', role_path ~ '/templates/namespace.j2' ) | from_yaml }}"

- name: remove user quota - clusterresourcequota
  k8s:
    state: absent
    definition: "{{ lookup('template', role_path ~ '/templates/clusterresourcequota.j2' ) | from_yaml }}"

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool